build: off
shallow_clone: true
skip_tags: true
skip_branch_with_pr: true
cache:
  - C:\strawberry
init:
  - git config --global core.autocrlf input
install:
  - if not exist "C:\strawberry" choco install strawberryperl
  - SET "PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%"
test_script:
  - curl -sSL --compressed https://git.io/cpm | perl - install -g App::cpm
